import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Game from "../components/Game/Game";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        league ability match
        <div>links</div>
      </header>

      <main className={styles.main}>
        <div>timer component</div>
        <div>game component, 5 boxes. 5 more every failure</div>
        <Game></Game>
      </main>

      <footer className={styles.footer}>
        <div>footer</div>
      </footer>
    </div>
  );
}
